theme: jekyll-theme-minimal
name: Erik Molenaar
title: Erik Molenaar
description: |
Welcome to my portfolio website. I'm a Game and Media Technology graduate looking for a game development programmer job.
I love games as a medium and everything involved in making them. I count dabbling in all of the things I do not yet know about game development as my hobbies, but would like, more than anything, to get to work in game development professionally as a programmer, tying all the aspects together and making each the best they can be.